modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/MoonflowerTeam/${repo}/issues"
license = "GPLv3"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Moonflower Studio"
credits = "Jackson"
description = "Pollen is a library mod which includes various utilities and platform bridges for Fabric and Forge using Architectury."
updateJSONURL = "https://github.com/MoonflowerTeam/${repo}/update.json"
#logoFile = ""

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17,)"
ordering = "NONE"
side = "BOTH"